### ISSUE TITLE
install not success

### ISSUE THREAD

**Issue by yfj1963** [xlwings/git-xl#45]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "subprocess.py", line 1083, in _readerthread
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in
ultibyte sequence

Traceback (most recent call last):
  File "cli.py", line 344, in <module>
  File "cli.py", line 260, in execute
  File "cli.py", line 289, in install
  File "cli.py", line 63, in __init__
  File "cli.py", line 128, in get_global_gitconfig_dir
  File "cli.py", line 122, in execute
  File "subprocess.py", line 425, in run
  File "subprocess.py", line 863, in communicate
  File "subprocess.py", line 1133, in _communicate
IndexError: list index out of range
[101984] Failed to execute script cli

C:\Users\yfj>git xltrail install
git: 'xltrail' is not a git command. See 'git --help'.

**Comment by yfj1963** [comment]
please help me to look at this problem?

**Comment by yfj1963** [comment]
my command is git xl install

**Comment by fzumstein** [comment]
What are your regional/language settings?

**Comment by yfj1963** [comment]
Im in china,  Python 3.4.1  version, and chinese language in windows . Excuse me， this tool supported on linux?

**Comment by fzumstein** [comment]
currently, the tool is only supported on Windows

**Comment by iansedano** [comment]
I had similar issue. After installing exe, at command line, it wouldn't recognize `git xl install`  but after restarting my computer it worked no problem.

**Comment by pifeifei** [comment]
+1

**Comment by willcream** [comment]
if the owner doesn't agree my pull request yet, @yfj1963 u can build yourself 
clone this repository and modify the `cli.py` with these:
```
subprocess.run(xxxx) --> subprocess.run(xxxx, encoding='utf-8')
```
and then, use virtualenv or not to install requirement and pyinstaller, build the exe for yourself. And add the exe folder path in your environment
