### ISSUE TITLE
[12304] Failed to execute script diff -- can't find "C:\dev\null"

### ISSUE THREAD

**Issue by charbonw** [xlwings/git-xl#49]
git diff fails with this message:

```
[12304] Failed to execute script diff
Traceback (most recent call last):
  File "diff.py", line 28, in <module>
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\dev\null'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Aspose.Cells.Workbook.^B(String ^B, LoadOptions ^C)
   at xltrail.core.Workbook..ctor(String path)
fatal: external diff died, stopping at filename.xlsm
```

I'm running git-xl-windows-0.4.1. I've tried restarting my computer and reinstalling the software, to no effect. This extension has worked for me in the past, but always fails on this file.

**Comment by fzumstein** [comment]
fixed by #53
