### ISSUE TITLE
Does git-xl support chinese yet?

### ISSUE THREAD

**Issue by berxtjkl** [xlwings/git-xl#64]
![image](https://user-images.githubusercontent.com/18417195/118611103-11e1a780-b7ef-11eb-957c-1cc23bd75a87.png)
I am using git diff in a Chinese window 10 environment, but it shows the above error.
I have downloaded and installed the 0.5.0 exe of [xltrail ](https://www.xltrail.com/git-xl), and I have run the command
`git xl install and git xl install --local`
Both won't fix the issue above, I am guessing whether it's because it does not support Chinese yet, 
Anyway, thanks for sharing this wonderful tool, I think this really helps.

**Comment by fzumstein** [comment]
That's a bug, thanks for reporting, @berxtjkl!

**Comment by phobo3s** [comment]
i think i have the same issue. How can i solve it?

`-Dim httpReq As New MSXML2.XMLHTTP60
Traceback (most recent call last):
  File "diff.py", line 80, in <module>
  File "colorclass\windows.py", line 275, in write
  File "encodings\cp1254.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xfd' in position 103: character maps to <undefined>
[8252] Failed to execute script 'diff' due to unhandled exception!
fatal: external diff died, stopping at Investor/Probtest/Pay.xlsm`
